micronaut:
  application:
    name: test-course-template
  server:
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: supaDupaSecretThatNobodyWillKnow
my:
  storage:
    dataDir: ".volumes/data"
    dataSyncPeriodSeconds: 10
    backupDir: ".volumes/backup"
    backupPeriodSeconds: 3600
    maxBackups: 10
